name: 'LGTM Lottery'
description: 'Posts a random LGTM image to PR or Issue comments'
branding:
  icon: 'smile'
  color: 'orange'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  pattern:
    description: 'Regular expression to match LGTM comments'
    default: '^(lgtm|LGTM)$'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    PATTERN: ${{ inputs.pattern }}
