name: LGTM Action

on:
  issue_comment:
    types: [created]

jobs:
  lgtm-job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Custom LGTM Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
